import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/dimos2.webp";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import Link from "next/link";
import HireMe from "@/components/HireMe";
import runner from "../../public/images/svgs/runner_final.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dimos | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-ful min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                alt="Dimos"
                src={profilePic}
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Plan And Train."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Choosing me as your personal trainer is an investment in
                excellence and expertise. Specializing in track and field, I am
                bringing a wealth of knowledge, proven training techniques, and
                a passion for athletics to every session. With a personalized
                approach, he focuses on your unique strengths and goals,
                ensuring optimal performance and injury prevention. His
                dedication, experience, and motivational coaching style empower
                athletes of all levels to reach new heights. Trust me to guide
                you on your journey to athletic success and unparalleled
                fitness.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dimos_cv.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                  text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid 
                  border-transparent hover:border-dark dark:bg-light dark:text-dark
                   hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:dimos_96@hotmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-52 md:hidden">
          <Image src={runner} alt="runner" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
